spring:
  application:
    name: customer-management-dlq-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka
          zk-nodes:
          - kafka
      bindings:
        ordersIn:
          group: customer-management-service
          destination: error.es-orders.customer-management-service
        
server:
  port: 8484