spring:
  application:
    name: customer-management-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka
          zk-nodes:
          - kafka
        bindings:
          ordersIn:
            consumer:
              enable-dlq: true
          ordersOut:
            producer:
              sync: false
      bindings:
        ordersIn:
          group: customer-management-service
          destination: es-orders
          consumer:
            max-attempts: 4
        ordersOut: 
          destination: es-orders
          content-type: application/json
        
server:
  port: 8282