spring:
  application:
    name: order-management-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka
          zk-nodes:
          - kafka
        bindings:
          ordersOut:
            producer:
              sync: false
      bindings:
        ordersIn:
          group: order-management-service 
          destination: es-orders
        ordersOut: 
          destination: es-orders
          content-type: application/json
        
server:
  port: 8080